In [1]:
import torch 
print(torch.__version__)

2.2.0+cpu


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as python int
scalar.item()

7

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.tensor([[[3, 4, 5], 
                        [4, 5, 6], 
                        [7, 8, 9]]])
TENSOR

tensor([[[3, 4, 5],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
random_tensor = torch.rand(4, 2, 3, 4)
random_tensor

tensor([[[[0.2888, 0.1193, 0.2383, 0.8382],
          [0.3970, 0.3345, 0.6085, 0.1755],
          [0.2793, 0.2063, 0.6925, 0.9557]],

         [[0.3751, 0.5381, 0.5989, 0.1764],
          [0.3294, 0.1250, 0.6657, 0.5937],
          [0.2769, 0.1938, 0.3307, 0.8310]]],


        [[[0.0906, 0.4526, 0.5478, 0.1277],
          [0.5438, 0.3122, 0.7473, 0.1953],
          [0.0246, 0.1054, 0.2013, 0.6876]],

         [[0.5480, 0.9547, 0.3004, 0.3053],
          [0.6603, 0.6643, 0.2571, 0.7100],
          [0.2553, 0.3126, 0.6306, 0.0192]]],


        [[[0.4247, 0.4390, 0.4787, 0.1487],
          [0.0793, 0.8499, 0.4856, 0.7545],
          [0.8015, 0.2634, 0.0463, 0.7505]],

         [[0.2171, 0.0600, 0.0881, 0.7050],
          [0.9524, 0.8237, 0.5834, 0.6214],
          [0.7182, 0.9529, 0.2107, 0.7328]]],


        [[[0.9975, 0.3720, 0.1227, 0.1066],
          [0.9848, 0.0418, 0.0202, 0.5377],
          [0.2463, 0.9880, 0.6035, 0.3264]],

         [[0.5723, 0.5171, 0.3154, 0.2254],
          [0

In [16]:
random_tensor.shape

torch.Size([4, 2, 3, 4])

In [17]:
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channel
random_image_tensor.shape

torch.Size([224, 224, 3])

In [18]:
random_image_tensor.ndim

3

In [19]:
zero_to_nine = torch.arange(0, 10)
zero_to_nine

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
torch.zeros_like(input=zero_to_nine)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
t1 = torch.tensor([3.0, 6.0, 9.0],
                  dtype=None, # What datatype is tensor(Eg. float32 or float16)
                  device=None, # What device is your tensor on("cuda"/"cpu")
                  requires_grad=False) # whether or not to track gradients
t1

tensor([3., 6., 9.])

In [22]:
t1.dtype

torch.float32

In [23]:
t2 = t1.type(torch.float16)
t2

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
torch.manual_seed(42)
torch.rand(3, 4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])